version: 2.1

# orbs
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.8.2

# jobs
jobs:
  build:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Run tests..."
          npm run test --if-present
  publish:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14

      # The orb uses docker/check to verify environment variable configurations
      - docker/check

      # Build the image using credentials natively managed by the orb
      - docker/build:
          image: moradhi1/circleci-docker-test
          tag: v1.0.3
          registry-username: DOCKER_LOGIN
          registry-password: DOCKER_PASSWORD

      # Push the image using those same credentials
      - docker/push:
          image: moradhi1/circleci-docker-test
          tag: v1.0.3
          registry-username: DOCKER_LOGIN
          registry-password: DOCKER_PASSWORD

# workflow
workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
