version: 2.1

# orbs
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.8.2
  snyk: snyk/snyk@1.5.0

# jobs
jobs:
  build:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  scan:
    docker:
      - image: cimg/node:20.0.0
    environment:
      IMAGE_NAME: moradhi1/tamkeen-software:v1.0.3
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME

  codescan:
    docker:
      - image: cimg/node:20.0.0
    environment:
      IMAGE_NAME: moradhi1/tamkeen-software:v1.0.3
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/install
      - run: |
          snyk code test

  test:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Run tests..."
          npm run test --if-present

  publish:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: "Log in to Docker Hub"
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
      - run:
          name: "Build Docker Image"
          command: docker build -t moradhi1/tamkeen-software:v1.0.3 .
      - run:
          name: "Push Docker Image"
          command: docker push moradhi1/tamkeen-software:v1.0.3

  deploy:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Render Push
          command: |
            curl "https://api.render.com/deploy/srv-d90f7g9kh4rs739fcam0?key=R85QfylJRuU"

# workflow
workflows:
  simple_workflow:
    jobs:
      # Build and Test run on BOTH main and release branches
      - build:
          filters:
            branches:
              only:
                - main
                - release
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - release

      # Code scanning runs for BOTH main and release
      - scan:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - release
      - codescan:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - release

      # Publish runs on both main and release
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - main
                - release

      # Deploy runs ONLY on the release branch
      - deploy:
          requires:
            - publish
          filters:
            branches:
              only: release