version: 2.1

# orbs
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.8.2

# jobs
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build Application Assets
          command: npm run build

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Tests
          command: npm run test --if-present # Prevents crashing if we don't have tests written yet

  publish:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - docker/check

      # Log in to Docker Hub using environment variables
      - docker/login:
          username: DOCKER_LOGIN
          password: DOCKER_PASSWORD

      # Build and Push Original Project (v1.0.0)
      - docker/build:
          image: moradhi1/circleci-docker-test
          tag: v1.0.0
      - docker/push:
          image: moradhi1/circleci-docker-test
          tag: v1.0.0

      # 3. Build and Push Updated Title Project (v1.0.1)
      - docker/build:
          image: moradhi1/circleci-docker-test
          tag: v1.0.1
      - docker/push:
          image: moradhi1/circleci-docker-test
          tag: v1.0.1

# workflow
workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
